### ISSUE TITLE
是否支持持久化

### ISSUE THREAD

**Issue by visionarywind** [Memorydoc/gobrs-async-starter#12]
是否考虑支持持久化？很多场景这是个硬需求呢

**Comment by Memorydoc** [comment]
指的是编排规则持久化吗？  后续开放dashboard平台进行配置持久化和监控相关功能。

**Comment by visionarywind** [comment]
task的持久化，如果task执行的机器意外宕机，重启后可以继续执行
跟规则可能有相同之处，编排规则可能是无太多状态的，而task是可能包含状态的

**Comment by Memorydoc** [comment]
规则配置本身就是在配置文件中写好的，你的意思应该是任务状态执行过程中宕机的话是不支持维护这个状态的

**Comment by ponfee** [comment]
> 过程中宕机的话是不支持维护这个状态的

这个项目支持task持久化，可以参考下看是否满足你的需求
https://github.com/ponfee/distributed-scheduler
