### ISSUE TITLE
A,B,C->D:any并发调用ABC时，有条件优先返回执行D

### ISSUE THREAD

**Issue by fgs2008** [Memorydoc/gobrs-async-starter#17]
A,B,C->D:any并发调用ABC,ABC谁先返回就执行D时，是否可以支持根据ABC执行结果状态来决定是否执行D，优先返回的任务不满足条件 则继续等待其他任务执行结果，ABC返回时需要包装任务执行结果的返回值。

**Comment by daidai21** [comment]
A,B,C ->E->D:any

加个E节点，专门处理这个逻辑？

**Comment by Memorydoc** [comment]
已发布该功能
