### ISSUE TITLE
fail的时候导致程序卡主

### ISSUE THREAD

**Issue by yuzd** [Memorydoc/gobrs-async-starter#2]
发现一个问题，如果我只有一个task 且 走到fail里面了 且默认是fail不支持subtask
那么 会导致程序卡住。走不到最后一个TerminationTask

![image](https://dimg04.c-ctrip.com/images/0v52l120009f9d4m02194.png)

![image](https://dimg04.c-ctrip.com/images/0v526120009f9emt18185.png)

**Comment by Memorydoc** [comment]
该问题已修复，重新拉一下源码

**Comment by yuzd** [comment]
已确认修复
效率真高，真6真给力
