### ISSUE TITLE
master-v2 任务异常后整体阻塞

### ISSUE THREAD

**Issue by icom2014** [Memorydoc/gobrs-async-starter#22]
master v2 中：A->B->C  如果B 异常抛出。整体阻塞。
master 中，无该问题。

**Comment by Memorydoc** [comment]
是哪个测试用例？

**Comment by icom2014** [comment]
- name: "general"
          content: "AService->BService->FService"

---
 @Override
    public Object task(Object o, TaskSupport support) {
        System.out.println("BService Begin");
        for (int i1 = 0; i1 < i; i1++) {
            i1 += i1;
        }
        System.out.println(1 / 0);  // 异常
        System.out.println("BService Finish");
        return null;
    }

**Comment by Memorydoc** [comment]
重新拉一下试试
