### ISSUE TITLE
gobrs-async-core依赖下载不了

### ISSUE THREAD

**Issue by shuigedeng** [Memorydoc/gobrs-async-starter#26]
1. implementation "io.github.memorydoc:gobrs-async-starter:1.2.5-RELEASE"

2.里面的依赖 com.jd.gobrs:gobrs-async-core:1.0.5-SNAPSHOT 在公网下载不了

**Comment by Memorydoc** [comment]
最新版本也下载不了吗?

**Comment by Memorydoc** [comment]
拉取最新代码已经修复
