### ISSUE TITLE
版本兼容问题

### ISSUE THREAD

**Issue by lijing0324** [Memorydoc/gobrs-async-starter#3]
1.在微服框架中alibaba版本为2021.1,spring-boot版本为2.5.6时候会出现无法加载GobrsSpring这个类的情况
![image](https://user-images.githubusercontent.com/104116303/168509892-8eff419d-eea4-4844-a3da-329abf8fab6e.png)
2.同时banner会打印多次
![image](https://user-images.githubusercontent.com/104116303/168510412-982c58b5-6225-483b-bc9f-0d9118c108a6.png)

**Comment by Memorydoc** [comment]
感谢反馈，已经修复
