### ISSUE TITLE
http get path does not exist

### ISSUE THREAD

**Issue by selectbook** [Memorydoc/gobrs-async-starter#5]
In the quick start doc, how to run demo gives the http get path http://localhost:8888/gobrs/testGobrs, but the RequestMapping name of gobrsTest method in GobrsController is test.

As a result, there is a 404 error: There was an unexpected error (type=Not Found, status=404).

**Comment by azhsmesos** [comment]
这个可以assiged给我吗，想参与到gobrs-async的开源贡献中来

**Comment by Memorydoc** [comment]
请添加17615195790微信 加入&nbsp;dromara-gobrs-async 交流沟通&nbsp;


花落无声
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月10日(星期五) 上午10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [dromara/gobrs-async] http get path does not exist (Issue #5)





 
这个可以assiged给我吗，想参与到gobrs-async的开源贡献中来
